### PR TITLE
87 improve exception messages

### LINKED ISSUE #87: Error messages for add and export function parsing are not descriptive enough
image

### PR DESCRIPTION
**Pull request by guangxuan**
Add specialized exception messages for Add and Edit buyer/property depending on given actor
Add preamble expectations for Add/Edit commands.
Add SimpleCommand extends Command for testing purposes.
Add ExportCommandParserTest
Add AddBuyerCommand Tests

TODO: EditBuyerCommand tests

Discussion:
which exception message should "add" or "edit" as a command give? 
closes #87

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/property/EditPropertyCommand.java [hunk 1]
```diff
@@ -32,6 +41,29 @@
 
     public static final String MESSAGE_EDIT_PROPERTY_SUCCESS = "Edited Property: %1$s";
     public static final String MESSAGE_DUPLICATE_PROPERTY = "This property already exists in the address book.";
+    public static final String MESSAGE_USAGE = COMMAND_WORD + " property: Edits the details of the property identified "
+            + "by the index number used in the displayed property/buyer list. "
```
Comment (sunjc826) [inline src/main/java/seedu/address/logic/commands/property/EditPropertyCommand.java:45]:
```
+ "by the index number used in the displayed property list. "
```

File: src/main/java/seedu/address/logic/parser/EditCommandParser.java [hunk 2]
```diff
@@ -53,24 +53,20 @@ public EditCommand parse(String args) throws ParseException {
             actor = ParserUtil.parseActor(preamble, ACTOR_POSITIONAL_INDEX);
             index = ParserUtil.parseIndex(preamble, INDEX_POSITIONAL_INDEX);
         } catch (ParseException pe) {
-            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT, EditCommand.MESSAGE_USAGE), pe);
+            throw new ParseException(String.format(MESSAGE_INVALID_PREAMBLE, argMultimap.getPreamble(),
+                    EditCommand.EXPECTED_PREAMBLE));
```
Comment (sunjc826) [inline src/main/java/seedu/address/logic/parser/EditCommandParser.java:57]: Should there be a `pe` in the last argument like before the diff?

File: src/test/java/seedu/address/logic/parser/AddCommandParserTest.java [hunk 3]
```diff
@@ -33,13 +35,16 @@
...
 import static seedu.address.logic.parser.CommandParserTestUtil.assertParseSuccess;
+import static seedu.address.logic.parser.ParserUtil.MESSAGE_INVALID_PREAMBLE;
 import static seedu.address.testutil.TypicalProperties.P_AMY;
 import static seedu.address.testutil.TypicalProperties.P_BOB;
 
 import org.junit.jupiter.api.Disabled;
 import org.junit.jupiter.api.Test;
 
 import seedu.address.logic.commands.AddCommand;
+import seedu.address.logic.commands.EditCommand;
```
Comment (sunjc826) [inline src/test/java/seedu/address/logic/parser/AddCommandParserTest.java:46]: There's an unused import here, along with some others, although CI will catch this once the trailing whitespace issues are fixed.

File: src/main/java/seedu/address/logic/commands/buyer/EditBuyerCommand.java [hunk 4]
```diff
@@ -29,6 +34,21 @@
 public class EditBuyerCommand extends EditCommand {
     public static final String MESSAGE_EDIT_BUYER_SUCCESS = "Edited Buyer: %1$s";
     public static final String MESSAGE_DUPLICATE_BUYER = "This buyer already exists in the address book.";
+    public static final String MESSAGE_USAGE = COMMAND_WORD + " buyer: Edits the details of the buyer identified "
+            + "by the index number used in the displayed property/buyer list. "
```
Comment (sunjc826) [inline src/main/java/seedu/address/logic/commands/buyer/EditBuyerCommand.java:38]:
```
+ "by the index number used in the displayed buyer list. "
```

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 5]
```diff
@@ -47,12 +47,16 @@ public AddCommand parse(String args) throws ParseException {
 
         Actor actor;
 
+        String preamble = argMultimap.getPreamble();
+        if (preamble.isEmpty()) {
```
Comment (sunjc826) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java:51]: On second thoughts, would `isBlank` be better? What do the others think?
