### PR TITLE
Fix unchecked cast compile warnings in UniqueList

### LINKED ISSUE #77: UniqueList.java: uses unchecked or unsafe operations.
Compile warning

### PR DESCRIPTION
**Pull request by trxe**
closes #77.

Changed all raw `UniqueList` to `UniqueList<Item>` where applicable.

### CODE REVIEW

**Review by waynetee — CHANGES_REQUESTED** [review]
image
compile warning remains for me, is it working for you?

**Comment by trxe** [comment]
it works for me

File: src/main/java/seedu/address/model/property/UniqueList.java [hunk 1]
```diff
@@ -119,7 +119,7 @@ public void sortListables(Comparator<Item> comparator) {
     public boolean equals(Object other) {
         return other == this // short circuit if same object
                 || (other instanceof UniqueList // instanceof handles nulls
-                        && internalList.equals(((UniqueList) other).internalList));
+                        && internalList.equals(((UniqueList<Item>) other).internalList));
```
Comment (sunjc826) [inline src/main/java/seedu/address/model/property/UniqueList.java:122]: unchecked_warning
